# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/subsystem_clock.xdc

# XDC: imports/sysgen/subsystem.xdc

# Block Designs: bd/Subsystem_bd/Subsystem_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_bd || ORIG_REF_NAME==Subsystem_bd} -quiet] -quiet

# IP: bd/Subsystem_bd/ip/Subsystem_bd_Subsystem_1_0/Subsystem_bd_Subsystem_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_bd_Subsystem_1_0 || ORIG_REF_NAME==Subsystem_bd_Subsystem_1_0} -quiet] -quiet

# XDC: c:/Users/gaherere/Desktop/derniereChance/netlist/ip_catalog/subsystem.gen/sources_1/bd/Subsystem_bd/Subsystem_bd_ooc.xdc
